### ISSUE TITLE
Error running aah cli 'build' on certain projects after upgrading go1.11 to 1.12

### ISSUE THREAD

**Issue by joelsdc** [go-aah/aah#253]
#### What version of aah are you using (`aah --version`)?

```
$ aah --version
aah v0.12.3
cli v0.13.4
go  v1.12.1
```

#### Does this issue reproduce with the latest release?

Yes

#### What operating system are you using (such as macOS, Linux and Windows)?

macOS Mojave

#### What did you do?

Build a static binary of my project

#### What did you expect to see?

The single binary built ;)

#### What did you see instead?

A build error

#### Additional context

When building a single image binary (also happens with regular build) I get the following error:
```
FATAL
# git.xxx.com/zzz/app/generated
app/generated/add_controllers.go:45:42: undefined: models

exit status 2
```

#### Extra info

Some extra info to hopefully help you troubleshoot:

1. This started happening after upgrading from go1.11.X to go1.12.1
2. I was able to have a scenario were certain projects would build, and others would give the above error.

Workaround:

Reinstall `aah cli`:
```sh
curl https://aahframework.org/install-cli | bash
```
 and then rebuild the project:
```sh
$ aah b -s
...
Build successful for 'zzz' [git.xxx.com/zzz]
Application artifact is here: /Users/joel/git/zzz/build/zzz-ff3c0e5-dirty-darwin-amd64.zip
```

Thanks!
Joel.

**Comment by joelsdc** [comment]
# Steps to reproduce:

AFAIR:

1. Have go1.11.latest installed.
2. Install aah
3. Builds you project
4. Update to go1.12.1
5. Build your project again <-- here it failed.
6. Reinstall aah
7. Build again <-- this one works.

**Comment by jeevatkm** [comment]
@joelsdc Thanks for reporting an issue.

**Comment by joelsdc** [comment]
Hi @jeevatkm, I think we can summarize that you have to rebuild the `cli` after every go version upgrade. 

Is there any way around this?
